const Premiere = [
  {
    id: "Black Adam",
    Format: "4K",
    Language: "English, Audio(4), Subtitles(1)",
    Duration: "2h 5m",
    Genre: "Action, Fantasy, Sci-Fi",
    Date: "20 Oct, 2022",
    Cost: "699",
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:q-80/et00117411-zmudrhhzzz-portrait.jpg",
  },
  {
    id: "Top Gun : Maverick",
    Language: "English, Audio(4), Subtitles(1)",
    Duration: "2h 11m",
    Genre: "Action, Drama",
    Date: "27 May, 2022",
    Cost: "119",
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:q-80/et00076943-smkpwvadsk-portrait.jpg",
  },
  {
    id: "Tumi O Tumi",
    Language: "Bengali, Audio(1), Subtitles(1)",
    Duration: "2h 2m",
    Genre: "Drama",
    Date: "17 Jan, 2022",
    Cost: "150",
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00119947-ednhelsdft-portrait.jpg",
  },
  {
    id: "Detection of Di-Renji",
    Language: "Mandarin, Audio(4), Subtitles(1)",
    Duration: "1h 33m",
    Genre: "Action, Mystery, Thriller",
    Date: "12 Jan, 2020",
    Cost: "29",
    src: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@bms_premiere_v1.png,oit-false,ofo-bottom_left:q-80/et00338333-xmuuathedf-portrait.jpg",
  },
  {
    id: "Nightmare Neighborhoud Moms",
    Language: "English, Audio(1), Subtitles(1)",
    Genre: "Drama, Thriller",
    Date: "8 Apr, 2020",
    Duration: "2h 13m",
    Cost: "179",
    src: "https://assets-in.bmscdn.com/iedb/movies/images/extra/vertical_logo/mobile/thumbnail/xxlarge/nightmare-neighborhood-moms-et00347059-1670850284.jpg",
  },
  {
    id: "Ebhabei Golpo Hok",
    Language: "Bengali, Audio(1), Subtitles(1)",
    Genre: "Drama",
    Date: "15 Oct, 2020",
    Duration: "1hr 53 mins",
    Cost: "119",
    src: "https://assets-in.bmscdn.com/iedb/movies/images/extra/vertical_logo/mobile/thumbnail/xxlarge/ebhabei-golpo-hok-et00145596-1672997391.jpg",
  },
  {
    id: "Ticket to Paradise",
    Language: "English, Audio(2), Subtitles(1)",
    Genre: "Comedy, Romantic",
    Date: "6 Oct, 2022",
    Duration: "1hr 44 mins",
    Cost: "149",
    src: "https://assets-in.bmscdn.com/iedb/movies/images/extra/vertical_logo/mobile/thumbnail/xxlarge/ticket-to-paradise-et00338333-1672044076.jpg",
  },
  {
    id: "Secret Headquarters",
    Language: "English, Audio(2), Subtitles(1)",
    Genre: "Action, Adventure, Comedy",
    Date: "12 Aug, 2022",
    Duration: "1hr 44mins",
    Cost: "699",
    src: "https://assets-in.bmscdn.com/iedb/movies/images/extra/vertical_logo/mobile/thumbnail/xxlarge/secret-headquarters-et00347789-1672912083.jpg",
  }
];

export default Premiere;
